INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'danielle', 'johnson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joshua', 'walker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jill', 'rhodes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'patricia', 'miller', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'robert', 'robinson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'william', 'gonzalez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'debra', 'gardner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeffrey', 'lawrence', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lisa', 'smith', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'linda', 'wolfe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'matthew', 'moore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'susan', 'rogers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'christopher', 'davis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'melanie', 'munoz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lindsay', 'blair', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'amanda', 'dudley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nicholas', 'arnold', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'maria', 'montgomery', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'michelle', 'ray', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'janet', 'williams', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeremy', 'roberts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jesse', 'garcia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cynthia', 'diaz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mitchell', 'clark', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joseph', 'zuniga', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'deborah', 'lynch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'george', 'daniel', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'frank', 'gray', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'veronica', 'bowman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'angela', 'cohen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'megan', 'parsons', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'antonio', 'stewart', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jason', 'hahn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nancy', 'edwards', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'diana', 'foster', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'robin', 'ellis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'john', 'hoffman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jose', 'richards', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rachael', 'ross', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'whitney', 'hicks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brandon', 'rodriguez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'courtney', 'conner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bryan', 'james', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'wendy', 'rice', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tasha', 'valencia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alexander', 'le', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'erin', 'herrera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'daniel', 'graham', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shawn', 'mckay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'vincent', 'white', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rita', 'harrell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kenneth', 'fowler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'chelsea', 'hernandez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kathryn', 'ryan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kimberly', 'moreno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'aaron', 'nguyen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'andrew', 'hickman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'natasha', 'decker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kyle', 'brown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'natalie', 'arroyo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'todd', 'jones', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kathleen', 'cannon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'david', 'alvarez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'andrea', 'baker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'monique', 'henderson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'amber', 'harris', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'larry', 'carney', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'samuel', 'holmes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brianna', 'hall', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'chad', 'welch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rebecca', 'heath', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'elizabeth', 'lewis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'selena', 'duncan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'thomas', 'mueller', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lindsey', 'lee', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'collin', 'jordan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rodney', 'owens', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jessica', 'nunez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tracey', 'powell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'james', 'west', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sandra', 'ramos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brent', 'kidd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mary', 'novak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sara', 'allison', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gabriel', 'tucker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'richard', 'galloway', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kristen', 'gibson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jennifer', 'phillips', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tanya', 'riley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'amy', 'adkins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brian', 'silva', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'wesley', 'farrell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'eric', 'yu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jacob', 'larson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'emma', 'young', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'pamela', 'sanchez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brooke', 'harvey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brandy', 'mills', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sarah', 'moran', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'randy', 'powers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kevin', 'walton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'charles', 'murillo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nicole', 'suarez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mike', 'bass', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jade', 'carr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'vanessa', 'valdez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alan', 'montoya', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sheila', 'taylor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'darrell', 'tran', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cassandra', 'robbins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tracy', 'whitehead', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'meghan', 'hill', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'adam', 'wise', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dana', 'green', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joyce', 'patterson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alec', 'ware', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brandi', 'anderson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rachel', 'flynn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'curtis', 'deleon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'christine', 'spears', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'theresa', 'cochran', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'angel', 'doyle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'martin', 'galvan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'leah', 'shields', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kristin', 'brennan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'michele', 'velasquez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'steven', 'torres', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'laura', 'perez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mark', 'lin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tammy', 'ramirez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'darlene', 'zavala', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tara', 'estes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ryan', 'chandler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lee', 'obrien', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'paul', 'scott', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeanne', 'frost', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'judy', 'lambert', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'michael', 'beck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ricky', 'martinez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shelby', 'byrd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'raven', 'gilbert', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'justin', 'carpenter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'scott', 'kennedy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gene', 'robertson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'loretta', 'potter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'emily', 'atkinson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'crystal', 'horton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'troy', 'douglas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'karen', 'carrillo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ronald', 'thompson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'april', 'wright', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'melinda', 'bryant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'laurie', 'contreras', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'caitlin', 'dodson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cheyenne', 'ball', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'phyllis', 'manning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jonathon', 'walsh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'katie', 'boyd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'chris', 'mitchell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'luis', 'fernandez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'devon', 'benson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jasmine', 'russell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jamie', 'fisher', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'heather', 'gates', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kathy', 'bell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'melissa', 'ashley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'julie', 'payne', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carrie', 'shelton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'frederick', 'mcdonald', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cindy', 'long', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'anne', 'day', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'derek', 'murray', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marie', 'king', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'zoe', 'santos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'denise', 'webster', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stefanie', 'caldwell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeffery', 'lyons', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gary', 'lawson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'danny', 'weiss', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tami', 'collins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'erica', 'rubio', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'hannah', 'burton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kendra', 'jefferson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'caroline', 'riggs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ross', 'wood', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lynn', 'reid', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'timothy', 'simon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mariah', 'keith', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cheryl', 'rosales', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'hunter', 'salinas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jacqueline', 'vaughan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'katherine', 'vaughn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'debbie', 'henry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bonnie', 'schmidt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'javier', 'washington', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jenny', 'bray', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alicia', 'campbell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'craig', 'ferguson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'terri', 'terry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'miranda', 'salas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'audrey', 'harrison', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jack', 'everett', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tim', 'short', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'edward', 'hart', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'victoria', 'wilson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'catherine', 'gibbs', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeremiah', 'hayes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jody', 'meza', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jared', 'guerrero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'glenn', 'wheeler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kelly', 'mann', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'grace', 'bradshaw', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'colleen', 'peck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rebekah', 'serrano', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kaitlyn', 'carroll', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'keith', 'barker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'holly', 'bender', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bill', 'reynolds', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marcus', 'hayden', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'barbara', 'sampson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'yvonne', 'chambers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'billy', 'avila', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sabrina', 'walters', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'travis', 'bailey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mathew', 'santiago', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mia', 'rivera', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sierra', 'cervantes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'leonard', 'morris', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'xavier', 'travis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'diane', 'daniels', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'helen', 'allen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marilyn', 'jimenez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tina', 'reyes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kristy', 'perry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lori', 'evans', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brenda', 'duarte', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'edgar', 'reed', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stanley', 'lopez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'heidi', 'armstrong', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jesus', 'rowe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bradley', 'garner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tyler', 'shaw', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brittany', 'kane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'morgan', 'alexander', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stephen', 'bowen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'terrance', 'costa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'norman', 'higgins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'barry', 'mccall', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'corey', 'schultz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dustin', 'knight', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'christian', 'pitts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'roberta', 'thomas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jonathan', 'ballard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'briana', 'coleman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ashley', 'andrews', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tiffany', 'barrett', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ashlee', 'jennings', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lauren', 'gomez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'donna', 'massey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bethany', 'oconnor', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gregory', 'mata', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alyssa', 'mcintyre', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'makayla', 'olson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'darius', 'mccarty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'donald', 'levy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'krystal', 'carson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'anna', 'herman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'madison', 'blankenship', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sophia', 'vasquez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'colton', 'clay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ellen', 'paul', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sonya', 'barnes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'julia', 'burns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stephanie', 'foley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cory', 'stephens', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'raymond', 'charles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carla', 'buchanan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'casey', 'hubbard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'molly', 'murphy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dylan', 'lester', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'duane', 'tyler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mario', 'harmon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sonia', 'logan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'adrienne', 'maynard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bruce', 'mendoza', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gina', 'browning', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'charlene', 'kelley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'virginia', 'chavez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kayla', 'morgan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cody', 'simmons', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'elijah', 'leblanc', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carlos', 'rodgers', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'becky', 'bruce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'christina', 'gallegos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'henry', 'park', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'anthony', 'reese', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ebony', 'nelson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kari', 'gregory', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tommy', 'estrada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'randall', 'greene', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'adrian', 'turner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'derrick', 'burgess', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'omar', 'padilla', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'martha', 'drake', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bobby', 'morse', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jenna', 'butler', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'samantha', 'richard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alexandria', 'cook', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joel', 'morrison', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shane', 'glass', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'claudia', 'romero', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lance', 'wyatt', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'latoya', 'huang', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shannon', 'pacheco', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marc', 'nolan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gerald', 'kim', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alexandra', 'watson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'riley', 'harper', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kristina', 'holland', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cameron', 'cummings', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'philip', 'hurley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'latasha', 'li', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joanne', 'fox', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stacey', 'conley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'benjamin', 'miranda', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'francis', 'guerra', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kellie', 'lamb', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sean', 'goodman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'taylor', 'richardson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'juan', 'rose', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'wayne', 'vang', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lacey', 'thornton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ana', 'acosta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'allison', 'bauer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'candice', 'mendez', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'peter', 'kramer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kelsey', 'moss', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marvin', 'maxwell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'zachary', 'hays', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jon', 'mullins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'micheal', 'preston', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'manuel', 'parker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'stacy', 'cox', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'douglas', 'harrington', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'austin', 'osborne', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'patrick', 'bradley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cassie', 'rush', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nathan', 'hines', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'victor', 'hughes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jorge', 'griffin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'evelyn', 'flores', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'calvin', 'vance', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dominic', 'spencer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'miguel', 'lara', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'madeline', 'compton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dawn', 'cole', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'melvin', 'humphrey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'renee', 'martin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shelley', 'jacobson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'shelly', 'hopkins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marcia', 'may', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sue', 'webb', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gail', 'gonzales', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'colin', 'cruz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'erik', 'lane', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tyrone', 'landry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'destiny', 'ruiz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'phillip', 'norton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mason', 'wells', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'christie', 'ewing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jodi', 'clayton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'hailey', 'coffey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'krista', 'griffith', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cristina', 'randall', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'devin', 'bates', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'glen', 'barr', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'teresa', 'bush', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'logan', 'pope', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'noah', 'baird', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kelli', 'pierce', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'savannah', 'johns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tamara', 'brewer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sharon', 'gentry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'suzanne', 'howe', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'albert', 'bird', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sheena', 'stevens', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'penny', 'wilcox', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joe', 'molina', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'desiree', 'schwartz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kurt', 'sullivan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'paula', 'hendricks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dennis', 'dunn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jane', 'elliott', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'abigail', 'aguilar', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'beth', 'cooper', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'bryce', 'mcknight', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cesar', 'ortiz', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'felicia', 'stanley', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'alexis', 'warner', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'joy', 'morales', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jimmy', 'gordon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'malik', 'keller', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nichole', 'buck', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'connie', 'simpson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kristi', 'bennett', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'angelica', 'booth', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'rose', 'howard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'diamond', 'underwood', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'arthur', 'bradford', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'nathaniel', 'williamson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tony', 'madden', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'andre', 'craig', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cole', 'ochoa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'annette', 'branch', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gabriella', 'abbott', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'clayton', 'jackson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ariel', 'hodge', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brad', 'parrish', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'paige', 'lam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'chase', 'davenport', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'peggy', 'campos', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kim', 'riddle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'levi', 'ward', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carly', 'carter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gavin', 'snyder', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'johnathan', 'weber', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'brittney', 'oliver', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'leon', 'oconnell', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jeanette', 'fuentes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'vicki', 'hunter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tonya', 'goodwin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'russell', 'dixon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'beverly', 'johnston', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dan', 'nixon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'darren', 'shepard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'darin', 'sweeney', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'greg', 'castro', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'cristian', 'wiggins', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'janice', 'steele', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'deanna', 'cooke', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tricia', 'floyd', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'steve', 'mathews', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'haley', 'cantu', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jim', 'rios', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lawrence', 'ibarra', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kiara', 'haney', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'glenda', 'richmond', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carol', 'hurst', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'valerie', 'vega', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kaylee', 'mccormick', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'walter', 'miles', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'carl', 'hale', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'judith', 'yang', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jean', 'benton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'olivia', 'roman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'caleb', 'joseph', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'spencer', 'porter', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dakota', 'berry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'meredith', 'sloan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'harry', 'brock', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'trevor', 'barton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dalton', 'shea', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jaclyn', 'villegas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'leslie', 'owen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'louis', 'chan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'margaret', 'huff', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kaitlin', 'greer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'toni', 'colon', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lorraine', 'stephenson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'hector', 'frey', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jackie', 'hardin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sheri', 'fry', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'grant', 'mcfarland', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ariana', 'mcgee', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'gloria', 'singleton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'lucas', 'lynn', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sherri', 'larsen', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jackson', 'mcclure', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'maurice', 'weaver', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'ray', 'marks', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'eddie', 'matthews', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'charlotte', 'prince', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'misty', 'mccann', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marissa', 'hood', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'monica', 'kline', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'tammie', 'vincent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'katrina', 'burke', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'johnny', 'trujillo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'eileen', 'bridges', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'kent', 'yoder', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jordan', 'price', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'howard', 'stokesF', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'isaac', 'frazier', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'sheryl', 'mason', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'mikayla', 'dickerson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'marco', 'whitaker', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'maxwell', 'chapman', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'caitlyn', 'barron', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'dorothy', 'rivas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO NAME_REGISTRY (ID, FIRST_NAME, LAST_NAME, CREATED_DATE, VERSION)
VALUES (NEXT VALUE FOR NAME_REGISTRY_SEQ, 'jerry', 'hinton', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
